name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step .NET
        uses: action/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./BaseDotNet.sln

      - name: Build
        run: dotnet build ./BaseDotNet.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./BaseDotNet.sln --configuration Release --no-build
